spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ticketnow}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.address=0.0.0.0
server.port=${PORT:8080}
fast2sms.api.key=${FAST2SMS_API_KEY:IXwkVUMfFcYb4sbAnj3drAtwGn52bl2uRF4Ys34ecSvcNrVaxgkfzyZSLDHz}