spring.datasource.url=jdbc:mysql://localhost:3306/ticketnow
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false



spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.address=0.0.0.0
server.port=8080
fast2sms.api.key=IXwkVUMfFcYb4sbAnj3drAtwGn52bl2uRF4Ys34ecSvcNrVaxgkfzyZSLDHz